name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install -g npm && npm -v
      - run: npm ci --workspaces
      - run: npm run build --workspaces
      - run: npm run test --workspaces
      - run: npm publish --workspaces
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
